---
- name: Install rpm file for Redhat Family (Amazon Linux, RHEL, and CentOS) 32/64-bit
  become: yes
  become_user: root
  yum:
    name: "https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm"
    state: present

- name: Start service amazon-ssm, if not started
  become: yes
  become_user: root
  service:
    name: amazon-ssm-agent
    state: started
